### ISSUE TITLE
Soulbind [empty slot]

### ISSUE THREAD

**Issue by brewk** [brewk/wowspreadsheet#53] opened 2020-12-09 13:25 UTC
Characters showing [empty slot] when the API doesn't indicate the slot was empty. Inspection of these characters api shows there may be something very wrong happening with the way we're assigning soulbinds to slots 

Example Character: Isneak Zuljin

**Comment by SKSniperSK** [comment] 2020-12-09 14:24
Sheet can show empty slot if there are multiple entries for the same tier (in the example of Isneak Zuljin it is tier 1 in API, tier 2 on the sheet) and one of the entries is empty. The code only shows one of the entries from a tier (the last in the API as far as sorting in Blizz API can be trusted) -> so this is the already known API bug.

**Comment by SKSniperSK** [comment] 2020-12-09 14:25
Duplicate of #39

**Closed as completed** 2020-12-09 15:49 UTC
Labels: bug, duplicate
